### PR TITLE
Synchronize open at login checkmark

### LINKED ISSUE #237: "Open at login" check mark not synced across all BitBar items
To reproduce:

* Setup multiple plugins
* Toggle "Open at Login" in one
* Check the 'check mark' on the other plugin
* Notice they do not sync

Potential solution:

* Trigger Refresh all when Open at Login option is changed

### PR DESCRIPTION
**Pull request by ksuther**
Fixes #237.
Also fixes another memory leak when enabling open at login, and a crash when disabling open at login.

### CODE REVIEW

**Comment by iosdeveloper** [comment]
👍

**Comment by iosdeveloper** [comment]
Please resolve conflicts with master.

**Comment by ksuther** [comment]
Done!

**Comment by iosdeveloper** [comment]
Please take a look @matryer since it closes the issue you opened.

**Comment by matryer** [comment]
Awesome work... let me review it now.

**Comment by iosdeveloper** [comment]
Open at login checkmark doesn't update at all and is not synchronized. I also don't see this change in 99ae162:

> Use validateMenuItem: to check the launch at login state so that updates across multiple plugins.

Reopening #237 for now.

**Comment by ksuther** [comment]
Submitted in #285. I must have rebased incorrectly when fixing the merge conflict.

**Pull request merged**
