### PR TITLE
add computer lock plugin

### PR DESCRIPTION
**Pull request by tomkinsc**
add a plugin to lock the computer, either via a sleep action or login
screen

screen shot 2016-01-05 at 11 24 15 am

### CODE REVIEW

**Comment by kousiktn** [comment]
Mac has a lock icon built-in. How will this be advantageous over that? 

To enable mac's default screen-locker - 
"Keychain access" -> "Preferences" -> "Show keychain status in Menu Bar"

**Comment by tomkinsc** [comment]
It's a template for adding pre-lock actions (disable wi-fi, set away messages, whatever). There are lines to either lock the screen (same as keychain lock action), or to return the user to the login window (same as fast user switching menu).

**Comment by matryer** [comment]
Hey @tomkinsc can you add this the README in the Plugin dir? And add your name to the contributors list (be sure to pull first). Thanks.

**Comment by tomkinsc** [comment]
Done!

**Comment by matryer** [comment]
... sorry it's conflicted now - could you resolve?

**Comment by tomkinsc** [comment]
Should be resolved!

**Comment by matryer** [comment]
Hey - thanks again for your plugin, in three short days we've added over 60 new amazing plugins. I wonder if you could take a minute to add a bit of metadata to your plugin?

Docs: https://github.com/matryer/bitbar#metadata

**Comment by tomkinsc** [comment]
Done! In https://github.com/matryer/bitbar-plugins/pull/67

**Pull request merged**
