### PR TITLE
Add Spotify Plugin

### PR DESCRIPTION
**Pull request by jtokoph**
Add Spotify plugin with track info and play/pause/next/previous actions.

### Paused State
screen shot 2016-01-04 at 10 10 42 pm

### Playing State
screen shot 2016-01-04 at 10 09 10 pm

### Not running
screen shot 2016-01-04 at 10 12 40 pm

### CODE REVIEW

**Comment by matryer** [comment]
OK wow - this might be the best plugin so far.

I hope you don't mind some suggestions?

* Instead of "Spotify Not Running", why not just have "Spotify"? Will take up less space but will make sense given the context. Or even just the little pause icon?

**Comment by jtokoph** [comment]
How about something like this?
screen shot 2016-01-05 at 12 45 20 am

**Comment by jtokoph** [comment]
Just updated it to be the music note (♫) by itself when not running.

**Comment by matryer** [comment]
Great work.

**Comment by jessor** [comment]
Btw, Emoji work, too ;-)

screen shot 2016-01-05 at 16 50 32

Press ⌘-Ctrl-Space for a characters palette.

**Comment by matryer** [comment]
Can you add that note to the plugin’s API?

**Pull request merged**
