### PR TITLE
Add templateImage parameter

### PR DESCRIPTION
**Pull request by ibutra**
Added a templateImage parameter as discussed in Slack.
This allows Mac OS X to change the styling in the StatusBar to fit the different themes better.

### CODE REVIEW

**Comment by iosdeveloper** [comment]
👍

**Comment by iosdeveloper** [comment]
We should add a [tutorial plugin](https://github.com/matryer/bitbar-plugins/tree/master/Tutorial) to show how to use images too.

**Comment by ibutra** [comment]
Alright, I try to think of one and make a pull request

**Comment by ibutra** [comment]
Pull request: https://github.com/matryer/bitbar-plugins/pull/290

**Pull request merged**
