### PR TITLE
added update check

### LINKED ISSUE #283: Check for latest version
Indicate a newer release in the version menu item and link to the release.

https://api.github.com/repos/matryer/bitbar/releases/latest

### PR DESCRIPTION
**Pull request by iosdeveloper**
closes #283

### CODE REVIEW

**Comment by vogonistic** [comment]
Do we need to have this refresh daily?

**Comment by iosdeveloper** [comment]
Maybe on `reset`, so on wake and "Refresh all".

**Comment by iosdeveloper** [comment]
This is what it looks like now:
screenshot

**Comment by iosdeveloper** [comment]
Perhaps we should also check if BitBar was installed via cask (i.e. cask exists and list contains bitbar) and in this case update, check if the cask is outdated and install on action.

**Comment by iosdeveloper** [comment]
@vogonistic Added with 293c17f

**Comment by tresni** [comment]
This looks fine to me.  I wonder if it makes sense to just do Sparkle as it handles checks and the actual replacement install for you.

**Comment by iosdeveloper** [comment]
@tresni Feel free to submit a PR for Sparkle at which point I'm fine with reverting this.

**Comment by tresni** [comment]
:+1: :shipit:

**Pull request merged**
