### PR TITLE
Feat submenu

### PR DESCRIPTION
**Pull request by shdev**
Hi,

first to say. BitBar is very cool and I like it a lot. I modified it a bit to have submenus. A big change is that it supports JSON as a line format. With this it was very easy to implement submenus
this a example row from a shell script:

```bash
echo '{"title":"SH","submenu":[{"title":"Oh Yeah"}]}'
````
every of the old parameters can used as json keys.

there are also some new parameters

- image --- a url of a image
- removeOnSuccess --- true removes the menu item after success of the shell script.

An other change is that a caution symbol appears, when a script terminates with exit status != 0

if you have questions feel free to contact me.

### CODE REVIEW

**Comment by matryer** [comment]
Would you be interested in contributing to the project? I'm considering a Swift rewrite?

**Comment by shdev** [comment]
I'm interested in the project. so I could contribute but my time very limited.

Swift is out of my range. I would like to use Swift, but there is no time to learn in the next time sorry.

**Comment by matryer** [comment]
Saving for v2.

**Comment by frakman1** [comment]
@shdev I cloned your repo and built binder but am unable to use your new son format. Can you provide an example of a file I need to put in the `BitBarPlugins` folder? I created a .sh file and put your one line example:
`echo '{"title":"SH","submenu":[{"title":"Oh Yeah"}]}'`

but nothing happened when I ran bitbar. No menu bar item was available.

**Comment by oleander** [comment]
@frakman1 I don't think there's any support for JSON in any of the version.

**Comment by frakman1** [comment]
There is support is shdev's fork (branch shdev:feat_submenu). That's what this page describes.

I got a bit further. I was on the wrong branch. Once I switched to the `feat_submenu`branch and recompiled, I was able to see the "SH" title but none of the json entries (title:Oh Yeah) showed up:
screen shot 2017-06-23 at 1 09 25 am

@shdev Do you have any suggestions?

**Pull request closed without merging**
