### PR TITLE
added distributable version

### LINKED ISSUE #164: Ability to bundle the app with customizations?
BitBar is great!

Is there a (documented) way to bundle the app to end users (people who would not necessarily want to or could create directories, follow technical directions, etc.), with a couple of plugins in it, so that we can ship the zip file and they just have to install the app?

I could not find much mention of how to do this in the docs or in the issues and I think it would be useful beyond BitBar itself and the more technical audience it caters to.

Ideally, we'd also like to give it a nice name (possibly including "BitBar" and/or a link and credits, of course) and customize some things to avoid confusion, like removing "run from terminal" and some preferences.

### LINKED ISSUE #180: Hide "Run in Terminal..." and "Preferences" menu items
I've only been playing around with this for a couple of minutes, so apologies if this is a duplicate question. Is it possible to hide the bottom section of a BitBar menu item?

bitbar-hide

I'd like to be able to deploy an instance of BitBar, but I don't want the user to be able to play around with its configuration once it's all setup.

Keep up the great work!
Morgan

### LINKED ISSUE #198: Deploying Bitbar in an environment
#164 

I have been using bitter for quite some time and its something I would like to deploy as part of our images, so that the IP is present on the menu bar for all users.

I have been able to deploy bitbar, and create a folder for the plugins and the location, but I have not been able by script or otherwise, to activate bitbar and tell it to use the plugin directory I assigned for it.

Is there a way to add these settings by command-line ? or is this something that would need to get added to bitbar ?

### LINKED ISSUE #236: Advanced items should be hidden behind Option key
The advanced items should only be visible when option+clicking the BitBar menu item.

Everything under the system separator should otherwise be invisible:

screen shot 2016-02-17 at 11 25 07

### PR DESCRIPTION
**Pull request by iosdeveloper**
- `pluginsDirectory` defaults to the app’s executables directory
- `userConfigDisabled` by default (#242)
- Introduces `DISTRO` preprocessor macro

The following are the (manual) steps needed to bundle plugins with the distributable version. We should ultimately create a script to do the work.

Take the distributable .app and scripts to bundle, copy them into the app bundle (via "Show Package Contents") and ensure they are executable.

`bitbar-bundler BitBarDistro.app one.10s.sh two.5m.sh three.7d.sh`

The bundler script could even download the plugins i.e. using GitHub paths (@matryer).

Ultimately closes #164, closes #170, closes #180, closes #198, closes #236 and closes #242.

What do the people who needed the feature think?

### CODE REVIEW

**Comment by iosdeveloper** [comment]
Travis fails because of the one analyzer warning generated by #235.

**Comment by iosdeveloper** [comment]
@cpg, @gilbertpalau, @mm2270, @morgrowe

**Comment by iosdeveloper** [comment]
This works for me: https://gist.github.com/iosdeveloper/1d8a9bf4cd3887538fd5

**Comment by mm2270** [comment]
@iosdeveloper Thanks for working on this issue. Its much appreciated!
I'd like to test out what you've put together here. I have some questions though.

First is, I assume since your PRs have not been merged yet, I will need to pull down your fork and compile the app? I ask because I pulled down the Xcode project and tried to build it and am running into build errors. I'm not a developer so my experience with Xcode is pretty limited, so I may be just committing a newbie mistake, but I see errors about no input files - it shows missing items in the `/App/Vendor/DateTools/` path and a few other places. I can post back with more specific info on that if you need it.

Second, by saying the plug-ins can go into the BitBar executable dir, do you mean literally in `/BitBar.app/Contents/MacOS/`? If so, would it make more sense to have them in the `Resources` dir instead? I think that's a more standard location for stuff like that to go, but maybe that's not really possible? Again, no developer here, so you tell me.

Lastly, what is the `bitbar-bundler` you reference above? Is that the macro you mentioned? Is this something available in your forked version?

Sorry for the ton of questions. I would just like to be able to test this and give feedback, but I'm a little confused on how to proceed with that.

**Comment by iosdeveloper** [comment]
@mm2270 Did you follow the instructions in the README? You need to run `git submodule init && git submodule update`.

If you add a Copy Files Build Phase with Destination Executables to the app target, `/Contents/MacOS/` is where the files go which makes sense because plugins are not just Resources they are executable and that is the standard location for that.

`bitbar-bundler` is the bundler script that would be added to the main repo eventually. Here is my implementation: https://gist.github.com/iosdeveloper/96b2d5038ac7587dc6a3

**Comment by mm2270** [comment]
Ah, no, I didn't, but I flipped this over to the GitHub Desktop app and that did the trick. Thanks! I'll play with this version a bit now.

**Comment by iosdeveloper** [comment]
You can now bundle plugins with the non-distributable version too and they will be symlinked in the plugin directory selected by the user. That allows us to bundle plugins while still allowing user configuration (like changing plugin folder).

**Comment by frakman1** [comment]
@iosdeveloper Thank you for the instructions. Although I can run the bundler on the .app and it successfully places the scripts into the MacOS folder, running the app still says "No plugins found"

Is the idea that the user would manually create the BitBarPlugins folder and place the scripts there? 
I thought that the app would just default to looking in the MacOS folder for its scripts.

**Pull request merged**
