### PR TITLE
Cleaning up the contentLine vs menu bar title lines

### PR DESCRIPTION
**Pull request by RaemondBW**
I found the difference between the allContentLines and allContentLinesAfterBreak to be very confusing. 

I renamed to something that makes sense.
Also made it so that if the title is a single line, it won't show in the main content view.
Removed blank lines so that the menu bar item doesn't appear invisible.

### CODE REVIEW

**Comment by matryer** [comment]
Fair enough - thanks.

**Comment by RaemondBW** [comment]
Should there not be a separate line for the title and an action? Otherwise there could be a third case added.

**Comment by jcaille** [comment]
I'm sorry, I don't really understand what you are suggesting ?

Do you mean having two lines ?

`Main title #Not shown in dropdown`
`Main title (with actions) | refresh=true #Shown in dropdown`

This does not seem straightforward.

The goal of the `dropdown=false` instruction was to allow this behaviour while keeping it opt-in (so that the default behaviour is preserved)

**Comment by RaemondBW** [comment]
No, What I am suggesting is that the title should be handled on it's own.
ex)
Main title
---
Menu bar item (with actions) #shown in dropdown

If you have a multi line title, it cycles through the lines before the first break and shows them in the main content.

If you want to have a simple single line output with action, this would be a new third case, where you duplicate the body into the title

**Comment by jcaille** [comment]
Ha Ok ! I see what you mean, thanks for the explanation.

This seems less straightforward than the existing default behaviour, but I don't really have an issue with this :)
The same behaviour could be achieved by outputting (which will work without special cases)

````
Main title | dropdown=false
---
Menu bar item | bash=foobar
````

Once again, thanks for the explanation.

**Comment by RaemondBW** [comment]
sorry I didn't see the dropdown change when I wrote this PR.

**Pull request merged**
