### PR TITLE
Add clipboard history plugin

### PR DESCRIPTION
**Pull request by jtokoph**
Another quick plugin I wanted for myself that I think would be valuable to others.

This plugin monitors your clipboard/pasteboard and maintains a history of items.

- Tracks up to 10 clipboard items.
- Clicking on a previous item will copy it back to the clipboard.
- Clicking "Clear history" will remove history files from the filesystem.
- Shows notification when copying or clearing

### Screenshots

screen shot 2016-01-05 at 4 26 28 am
screen shot 2016-01-05 at 4 19 31 am

### CODE REVIEW

**Comment by matryer** [comment]
FFS that's clever

**Comment by matryer** [comment]
Can you add it to the README list too please?

**Comment by jtokoph** [comment]
Dang you're quick on the merge. Didn't even have a chance to comment here :)

**Comment by matryer** [comment]
Please add your name and a link to the Contributors list on https://github.com/matryer/bitbar/blob/master/Plugins/README.md.

**Comment by matryer** [comment]
@jtokoph - could you add the [appropriate metadata](https://github.com/matryer/bitbar/blob/master/README.md#metadata) (and a screenshot) to https://github.com/matryer/bitbar-plugins/blob/master/System/clipboard-history.3s.sh ?

**Pull request merged**
