### PR TITLE
added bitbar:// path to refresh a plugin

### LINKED ISSUE #149: Ability to manually refresh from command  line.
Would be nice to have the ability to manually refresh a plugin via a command line call. Would be useful for event based things, like cmus notifications.

### LINKED ISSUE #216: Enable refresh=true for interactive processes
The goal is to enable processes that require interaction (i.e. can't use `terminal=false`) to refresh plugins on exit.

To [observe process lifetime without polling](https://developer.apple.com/library/mac/technotes/tn2050/_index.html#//apple_ref/doc/uid/DTS10003081-CH1-SUBSECTION10) we need the process ID (PID) that can be obtained using [`GetBSDProcessList`](http://stackoverflow.com/questions/2518160/programmatically-check-if-a-process-is-running-on-mac). There should also be a new parameter to specify the name of the process to observe.

Again I'm happy to submit a PR or make changes.

### PR DESCRIPTION
**Pull request by iosdeveloper**
usage: `open bitbar://refreshPlugin?name=...`

closes #149 and closes #216

### CODE REVIEW

**Comment by matryer** [comment]
Does `name` have to be the exact filename?

**Comment by matryer** [comment]
It would be cool if the `name` could omit the time and extension

**Comment by matryer** [comment]
maybe we say `prefix` instead of name? or allow wildcards?

**Comment by iosdeveloper** [comment]
I thought the exact name is already available from shell scripts with `$(basename "$0")`.

**Comment by matryer** [comment]
Yeah I'm thinking about refreshing _other_ plugins, or refreshing plugins from other scripts.

**Comment by iosdeveloper** [comment]
+1 for `prefix`. Implementing this later.

**Comment by iosdeveloper** [comment]
How about using predicates with the `LIKE` operator:

> `LIKE`
> The left hand expression equals the right-hand expression: `?`and `*` are allowed as wildcard characters, where `?` matches `1` character and `*` matches `0` or more characters.

(https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-215868)

**Pull request merged**
