### PR TITLE
Move target to 10.7

### LINKED ISSUE #282: 1.8 crashes if a loading plugin is refreshed
Steps to reproduce:
1. Refresh plugins with `Cmd-R`
2. While at least one plugin is loading, refresh the plugins again with `Cmd-R`
3. Crash

If NSZombies are turned on, this message is dumped:
`2016-03-16 12:13:41.790 BitBar[12034:2214293] *** -[ExecutablePlugin setContent:]: message sent to deallocated instance 0x6180001041d0`

The problem seems to be that self is deallocated at [ExecutablePlugin.m#L48](https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L48). One solution would be to create a new strong reference to self until after execution, or to use a `__weak` reference and `NSTask.terminationHandler`.

I also don't see how `if (weakSelf) {` will work with a `__unsafe_unretained` since the main difference between `__unsafe_unretained` and `__weak` is that `__weak` is set to nil when the reference is deallocated while `__unsafe_unretained` still points to the same address. [ExecutablePlugin.m#L83](https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L83)

Could we increase the deployment target to 10.7 so that `__weak` can be used?

### PR DESCRIPTION
**Pull request by tresni**
Use weak reference and fix #282

### CODE REVIEW

**Comment by iosdeveloper** [comment]
Please replace 10.6 in the README too.

**Comment by vogonistic** [comment]
I can't reproduce the crash on this branch. :+1:

**Comment by tresni** [comment]
I swear I looked for references to 10.6 and didn't see any.  But apparently I'm blind.  Fixing now

**Comment by iosdeveloper** [comment]
👍

**Comment by iosdeveloper** [comment]
Missing 10.6 references here (project)
https://github.com/tresni/bitbar/blob/target-10.7/App/BitBar.xcodeproj/project.pbxproj#L664
and here
https://github.com/tresni/bitbar/blob/target-10.7/App/BitBar.xcodeproj/project.pbxproj#L697

**Comment by tresni** [comment]
@iosdeveloper I thought tests inherited from the build projects, that'll teach me.  Set there, hopefully Travis passes now :)

**Comment by iosdeveloper** [comment]
They inherit from the project so you could have just changed the project. ;)

**Pull request closed without merging**
