### PR TITLE
Added `emojize` parameter to translate `:mushroom:` into :mushroom:

### LINKED ISSUE #269: Add support for `:emoji:` syntax
It'd be neat to support `:emoji:` to unicode translation. There are projects that extends NSString to add the functionality, so it's just about integrating it.

If you think it's a good idea. I can prepare a PR.

https://github.com/diy/nsstringemojize

### PR DESCRIPTION
**Pull request by vogonistic**
- Adds new param: `emojize=true`

Resolves #269

### CODE REVIEW

**Comment by matryer** [comment]
Why don't we just always do this? Rather than making it optional?

**Comment by vogonistic** [comment]
We had a discussion about that in #269

**Comment by iosdeveloper** [comment]
Travis fails because you didn't add the NSString Emojize category to the BitBarDistroTests target's Compile Sources Build Phase.

**Comment by vogonistic** [comment]
PR for Tutorial plugin: https://github.com/matryer/bitbar-plugins/pull/310

**Comment by iosdeveloper** [comment]
👍

**Pull request merged**
