### PR TITLE
Add standard deviation. Display :skull: icon when no internet connection.

### PR DESCRIPTION
**Pull request by trungdq88**
I have also fixed the capital letters as well.

### CODE REVIEW

**Comment by matryer** [comment]
Is there any way to make it easy for people to choose the domains? Perhaps a list at the top or an environment variable?

**Comment by trungdq88** [comment]
Sure there is way to do that. I'm not very good at shell script so feel free to modify this script as your will.
Things we could do to make it better:
- [ ] Store list of domain in an array (if shell script even has Array thing)
- [ ] Refactor the average and standard deviation calculation, right now it is hard coded and as a software engineer I feel bad about it.
- [ ] Stores the ping value history somewhere and make a graph for it (maybe useless, but cool feature though)
- [ ] Optimize the ping command to have less delay. This script uses `ping` to get the ping value and it took about 4 - 5 seconds to get the ping from all the domains, quite long. If we could reduce this, we can reduce the refresh time from 10 seconds to around 3 - 4 seconds to have the most realtime ping value.

**Comment by matryer** [comment]
Bash does have arrays - http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html

**Comment by matryer** [comment]
could just be an array at the top - default it with the ones you have, then a note telling people how to configure it?

**Comment by thealmightygrant** [comment]
I just submitted a fix for the issues on this PR: https://github.com/matryer/bitbar/pull/97. Sorry if I screwed up the github workflow. I hope that this fix helps some. Thanks for the great little project @matryer.

**Pull request merged**
