### PR TITLE
added iTunes plugin

### PR DESCRIPTION
**Pull request by daturkel**
I took a look at the [lovely Spotify plugin](https://github.com/matryer/bitbar/blob/master/Plugins/Music/spotify.10s.sh) and saw it was implemented in simple AppleScript. I ran a quick find-and-replace to swap out "Spotify" for "iTunes" and tested the functionality—everything still worked! Thus, this plugin duplicates the functionality of the spotify plugin *exactly*. 

Perhaps down the line someone would make one that checks for both iTunes and Spotify status, determines which one is in use, etc.

### CODE REVIEW

**Comment by matryer** [comment]
Please update the README in the Plugin folder with your plugin, and add your name to the contributors list.

**Comment by daturkel** [comment]
Done.

**Comment by matryer** [comment]
Hey - thanks again for your plugin, in three short days we've added over 60 new amazing plugins. I wonder if you could take a minute to add a bit of metadata to your plugin?

Docs: https://github.com/matryer/bitbar#metadata

**Comment by daturkel** [comment]
Already done!

**Pull request merged**
