### PR TITLE
Implement images for items

### PR DESCRIPTION
**Pull request by ibutra**
Implemented the ability to set images for items as discussed in Issue #32

### CODE REVIEW

**Comment by iosdeveloper** [comment]
Please check if `[NSData instacesRespondToSelector:@selector(initWithBase64EncodedString:options:)]` to prevent it from crashing on OS X < 10.9.

**Comment by ibutra** [comment]
Is implemented. Alternatively I could look into implementing that functionality myself to make it compatible with older versions of OS X. Would be interesting to know how many are using BitBar on OS X < 10.9 to decide whether it is worth the effort.

**Comment by iosdeveloper** [comment]
... and use https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSData_Class/#//apple_ref/occ/instm/NSData/initWithBase64Encoding: otherwise.

**Comment by ibutra** [comment]
Sorry, didn't see that. Now it should work.

**Comment by iosdeveloper** [comment]
:+1:

**Comment by mm2270** [comment]
I'm interested in using the new image param, but having a little trouble figuring out exactly how to add it in any scripts. Is there an existing example showing how to use this?

**Comment by iosdeveloper** [comment]
@mm2270 https://github.com/matryer/bitbar-plugins/pull/290

**Pull request merged**
