### PR TITLE
First hacky version of RescueTime plugin

### PR DESCRIPTION
**Pull request by kfdm**
Very rough mockup of plugin for [RescueTime](https://www.rescuetime.com/) to ask a few questions about style

1. So far, all of the plugin examples have been shell script, but I'm assuming the language does not matter so much as long as the user has it installed on their system. Are there any guidelines for that.

2. For my prototype, I've been a little hacky, and used a vendored library from a separately installed package for testing. Obviously one shouldn't do this for real, but it worked for my mock up. Are there any guidelines on how plugins with additional dependencies should be treated ?

3. This plugin requires an api key provided by RescueTime. Are there any guidelines how how to handle plugins that require an api key or other settings. I see one of the examples shows it as "add your api key here" in the source, but in generally it's frowned upon to commit things like API keys :)

4. Any guidelines on how errors would best be handled? For example, when web requests fail.

Thanks for a very neat script. It's been fun to play with it some this afternoon :+1:

### CODE REVIEW

**Comment by matryer** [comment]
Great questions.

1. Don't know - going to see how the project progresses before solving this
2. Don't know - going to see how the project progresses before solving this
3. Good point; there shouldn't be any API keys in the code
4. Some people have used a red colour in the output to indicate failure

**Comment by taylorzane** [comment]
To help answer question 1, I've tested a few languages to see how they perform, and to see if they required any hacks to work.

Languages that I have personally tested:
1. Ruby
  - Works without a hitch.
  - Use `puts "your string here"`
2. Python
  - Works without a hitch.
  - Use `print "your string here"` or `print("your string here")` for Python3
3. JavaScript (`node` CLI)
  - Works, but I had to do some hacking (that may be due to my setup though)
  - Shebang had to be in the format `#!/usr/bin/env /path/to/the/node/executable`
  - Use `console.log("your string here")`
  - `process.stdout.write` doesn't work correctly for some reason...
4. CoffeeScript (`coffee` CLI)
  - Works, required multiple hacks (again, this may be due to my env config.)
  - Shebang had to be in the format `#!/usr/bin/env /path/to/the/coffee/executable`
  - I had to modify the shebang in the `coffee` exe because it couldn't find `node`...
  - `coffee` shebang: `#!/usr/bin/env /path/to/the/node/executable`
  - Use `console.log "your string here"`
  - `process.stdout.write` doesn't work correctly for some reason...
5. Swift (Interpreted)
  - Works without a hitch.
  - Use shebang `#!/usr/bin/env swift`
  - Use `print("your string here")`
6. Swift (Compiled)
  - Works without a hitch.
  - You still need a file extension (I used `file.cswift`)
  - To compile a swift file, use: `xcrun -sdk macosx swiftc -o file.1s.cswift file.1s.swift`

**Comment by matryer** [comment]
I'm going to add this plugin - and we can move the future plugin discussion to https://github.com/matryer/bitbar/issues/112

@taylorzane - can we put your notes somewhere in the project for others? Maybe in a README somewhere?

**Comment by kfdm** [comment]
Sorry for the late reply.
Sounds good! I see you've documented a lot of things in the past few days and moved things to the over repo, so I'll clean up things over there. Thanks :)

**Pull request merged**
