### PR TITLE
Add PHP as tested language

### PR DESCRIPTION
**Pull request by SteveEdson**
(Also, shameless plug, I created a PHP formatter for making PHP Bitbar plugins a bit easier - https://github.com/steveedson/bitbar-php)

### CODE REVIEW

**Comment by matryer** [comment]
Let's link to your project in the PHP section?

**Comment by SteveEdson** [comment]
That would be great thanks

**Comment by matryer** [comment]
Do you want to update your PR with that?

**Comment by SteveEdson** [comment]
Yeah sure, is there a specific format being used for similar things?

**Comment by matryer** [comment]
No, you'll have to invent it :)

**Comment by matryer** [comment]
People will likely copy the way you do it.

**Comment by SteveEdson** [comment]
Hows that?

**Comment by matryer** [comment]
LGTM

**Comment by SteveEdson** [comment]
Cheers :+1:

**Pull request merged**
